name: Azure Static Web Apps CI/CD

on:
  workflow_dispatch:                # ✅ allow manual runs from the Actions tab
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false

      # ✅ quick sanity: confirm SWA token is present (value stays masked)
      - name: Check token exists
        run: |
          if [ -z "${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}" ]; then
            echo "❌ Missing AZURE_STATIC_WEB_APPS_API_TOKEN"; exit 1
          else
            echo "✅ Token is configured"
          fi

      # 🚀 Build & Deploy
      - name: Build And Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}   # use ONE consistent secret
          action: "upload"                                                                  # REQUIRED
          app_location: "/"                                                                 # repo root
          # api_location: "api"                                                               # keep ONLY if repo has /api with host.json
          output_location: ""                                                               # no build artifacts for plain static
          skip_app_build: true                                                              # skip frontend build (static)
          # api_build_command: ""                                                             # let Oryx handle Functions build if present
          repo_token: ${{ secrets.GITHUB_TOKEN }}                                           # enables PR comments

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}   # same secret
          action: "close"



